name: lint

on:
  push:
    branches:
      - "ci"
    tags:
      - "v*"
  pull_request:
    branches:
      - "ci"
    paths:
      - "lua/**"

jobs:
  lua-linter:
    name: "Linting with luacheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4

      - name: Use luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck *.lua lua/* tests/*
